services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: device_api
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d device_api"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    expose:
        - 5432
    networks:
      - devices-net
  api:
    image: devices-api:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "9001"
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: device_api
    ports:
      - "9001:9001"
    expose:
      - 9001
    networks:
      - devices-net

networks:
  devices-net:
    driver: bridge